version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: ai-travel-mate-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - ai-travel-mate-network

  postgresql:
    image: postgres:16
    container_name: ai-travel-mate-postgresql
    restart: unless-stopped
    ports:
      - "${POSTGRE_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRE_DATABASE}
      - POSTGRES_USER=${POSTGRE_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - ai-travel-mate-network


volumes:
  mongodb_data:
  mongodb_config:
  postgresql_data:

networks:
  ai-travel-mate-network:
    driver: bridge